services:
  - type: web
    name: talk-a-tive
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: your-mongodb-uri
      - key: JWT_SECRET
        value: your-jwt-secret
    autoDeploy: true
